Name:           ros-indigo-interactive-world-parser
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS interactive_world_parser package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/interactive_world_parser
Source0:        %{name}-%{version}.tar.gz

Requires:       jsoncpp-devel
Requires:       ros-indigo-interactive-world-msgs
Requires:       ros-indigo-jinteractiveworld
Requires:       ros-indigo-librms
Requires:       ros-indigo-rosbridge-server
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-tf2
BuildRequires:  jsoncpp-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-interactive-world-msgs
BuildRequires:  ros-indigo-librms
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-tf2

%description
The Main Parser for the Interactive World Database

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Jan 16 2015 Russell Toris <rctoris@wpi.edu> - 0.0.3-0
- Autogenerated by Bloom

* Tue Dec 16 2014 Russell Toris <rctoris@wpi.edu> - 0.0.2-0
- Autogenerated by Bloom

* Fri Dec 12 2014 Russell Toris <rctoris@wpi.edu> - 0.0.1-1
- Autogenerated by Bloom

* Fri Dec 12 2014 Russell Toris <rctoris@wpi.edu> - 0.0.1-0
- Autogenerated by Bloom

